### ISSUE TITLE
computer -architecture

### ISSUE THREAD

**Issue by shristabaruah** [nitish-awasthi/Invertians-Archive#29]
[Computer-Architecture-Organization.pdf](https://github.com/nitish-awasthi/Invertians-Archive/files/5395495/Computer-Architecture-Organization.pdf)

**Comment by Zenix27** [comment]
Hi @shristabaruah, ✋
I feel that you are new to **Open Source.** 😃
Let me explain it to you. 🧛

- When you open our repository, you would see a Fork option on the top right corner of the screen. I suggest you click that. and you will be directed to `shristabaruah/Invertians-Archive`.
- There you need to move to the respective folder, which in your case is `B.Tech./CSE/Books`.
- There you will be able to see multiple books. On top of them you will be able to see Add Files, then Upload, and there is where you will need to upload the **Computer Architecture** book and then click Commit Button below.
- After that, you will see an Option of Pull Request on the Repository's title bar. Click that, then create a pull request. Add required description then click Create.

**For more information see the video here** - https://www.youtube.com/watch?v=nT8KGYVurIU

**Comment by nitish-awasthi** [comment]
@shristabaruah I'm closing this issue. You can follow the above steps to make contributions.
